replicaCount: 1
image:
  repository: ghcr.io/dbildungsplattform/schulportal-client
  tag: ""
  pullPolicy: IfNotPresent

allowPrivilegeEscalation: ""
restartPolicy: Always


service:
  type: NodePort
  targetPort: 80  
  port: 80


frontendHostname: "helm.dev.spsh.dbildungsplattform.de"

###
ingress:
  ingressClassName: nginx
  pathType: Prefix
  httpRelativePath: "/"
  portnumber: 80