replicaCount: 1
namespace: ""
image:
  repository: ghcr.io/dbildungsplattform/schulportal-client
  tag: ""
  pullPolicy: IfNotPresent 

restartPolicy: Always
automountServiceAccountToken: false

frontendHostname: "helm.dev.spsh.dbildungsplattform.de"
commonLabels:
  name: spsh-client

selector:
  layer: spsh-client

ingress:
  ingressClassName: nginx
  pathType: Prefix
  httpRelativePath: "/"
  portnumber: 80

enabledserviceport:  true
ports:
  - protocol: TCP
    port: 80
    targetPort: 80

servicetype: NodePort
serviceName: http

containerPorts:
  http: 80