{{ if not .Values.dbpMoodle.restore.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-moodle-update-preparation-hook-serviceaccount"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  namespace: "{{ .Release.Namespace }}"
{{ end }}
