{{ if not .Values.dbpMoodle.restore.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-moodle-update-preparation-hook-serviceaccount"
  namespace: "{{ .Release.Namespace }}"
{{ end }}
