apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.releasename" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.commonLabels.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/layer: {{ .Values.selector.layer }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.commonLabels.name }}
        app.kubernetes.io/layer: {{ .Values.selector.layer }} 
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }} 
      containers:
        - name: {{ .Values.commonLabels.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }} 
        {{- if .Values.enabledcontainerSecurityContext }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
        {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.serviceName }} 
              containerPort:  {{ .Values.containerPorts.http }} 
      restartPolicy: {{ default "Always" .Values.restartPolicy }}