apiVersion: v2
appVersion: DBP-394
dependencies:
- condition: keycloakEnabled
  name: dbildungs-iam-keycloak-dev
  repository: ""
  version: '*'
description: dBildungs-IAM
name: dbildungs-iam
type: application
version: 0.0.0-dbp-394-20231129-1149
