apiVersion: v2
appVersion: DBP-352
dependencies:
- condition: keycloakEnabled
  name: dbildungs-iam-keycloak-dev
  repository: ""
  version: '*'
description: dBildungs-IAM
name: dbildungscloud-iam-server
type: application
version: 0.0.0-dbp-352-20231201-1326
