{{- if .Values.dbpMoodle.backup.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "moodle-backup-job"
subjects:
  - kind: ServiceAccount
    name: "moodle-backup-job"
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: "moodle-backup-job"
  apiGroup: rbac.authorization.k8s.io
{{- end -}}