apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-hook-rolebinding"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-hook-serviceaccount"
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-hook-role"
  apiGroup: rbac.authorization.k8s.io
