apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "moodle-cronjob"
subjects:
  - kind: ServiceAccount
    name: "moodle-cronjob"
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: "moodle-cronjob"
  apiGroup: rbac.authorization.k8s.io