{{- if .Values.dbpMoodle.restore.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-restore-job"
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-restore-job"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-restore-job"
  apiGroup: rbac.authorization.k8s.io
{{- end }}