{{- if (.Values.dbpMoodle.secrets.useChartSecret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "moodle"
  namespace: "{{ .Release.Namespace }}"
stringData:
  moodle-password: {{ include "dbpMoodle.secrets.moodle_password" . }}
  database-password-note: "Due to technical constraints, the database password key is always \"mariadb-password\" even if using PostgreSQL"
  mariadb-password: {{ include "dbpMoodle.secrets.database_password" . }}
  {{- if .Values.postgresql.enabled }}
  pgsql-admin-password: {{ include "dbpMoodle.secrets.database_root_password" . }}
  {{- end }}
  {{- if .Values.mariadb.enabled }}
  mariadb-root-password: {{ include "dbpMoodle.secrets.database_root_password" . }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis-password: {{ include "dbpMoodle.secrets.redis_password" . }}
  {{- end }}
  {{- if .Values.etherpadlite.enabled }}
  etherpad-postgresql-password: {{ include "dbpMoodle.secrets.etherpad_postgresql_password" . }}
  etherpad-api-key: {{ include "dbpMoodle.secrets.etherpad_api_key" . }}
  {{- end }}
{{- end }}