{{- if (.Values.dbpMoodle.secrets.useChartSecret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
stringData:
  moodle-password: {{ include "dbpMoodle.secrets.moodle_password" . }}
  {{- if .Values.postgresql.enabled }}
  mariadb-password: {{ include "dbpMoodle.secrets.mariadb_password" . }}
  pgsql-admin-password: {{ include "dbpMoodle.secrets.pgsql_admin_password" . }}
  {{- end }}
  {{- if .Values.mariadb.enabled }}
  mariadb-password: {{ include "dbpMoodle.secrets.mariadb_password" . }}
  mariadb-root-password: {{ include "dbpMoodle.secrets.mariadb_root_password" . }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  redis-password: {{ include "dbpMoodle.secrets.redis_password" . }}
  {{- end }}
  {{- if .Values.etherpadlite.enabled }}
  etherpad-postgresql-password: {{ include "dbpMoodle.secrets.etherpad_postgresql_password" . }}
  etherpad-api-key: {{ include "dbpMoodle.secrets.etherpad_api_key" . }}
  {{- end }}
{{- end }}