apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "moodle-database"
  namespace: "{{ .Release.Namespace }}"
stringData:
  {{ if .Values.moodle.mariadb.enabled -}}
  type: "mariadb"
  host: "moodle-mariadb-0"
  port: "3306"
  user: "{{ .Values.moodle.mariadb.username }}"
  name: "{{ .Values.moodle.mariadb.database }}"
  {{- else if .Values.moodle.externalDatabase -}}
  type: "{{ .Values.moodle.externalDatabase.type }}"
  host: "{{ .Values.moodle.externalDatabase.host }}"
  port: "{{ .Values.moodle.externalDatabase.port }}"
  user: "{{ .Values.moodle.externalDatabase.user }}"
  name: "{{ .Values.moodle.externalDatabase.database }}"
  {{- end }}

