{{- if and .Values.dbpMoodle.backup.enabled (not .Values.dbpMoodle.backup.gpgkeys.existingSecret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "moodle-backup-gpg-keys"
  namespace: "{{ .Release.Namespace }}"
data:
  {{- range $key, $value := .Values.dbpMoodle.backup.gpgkeys }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}