apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: moodle-config
  namespace: {{ .Release.Namespace }}
data:
  php.ini: {{ .Files.Get "scripts/php.ini" | b64enc }}
  config.php: {{ tpl (.Files.Get "scripts/config.php") . | b64enc }}