{{ if not .Values.dbpMoodle.phpConfig.existingConfig -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: moodle-php-config
  namespace: {{ .Release.Namespace }}
data:
  config.php: {{ tpl (.Files.Get "scripts/config.php") . | b64enc }}
{{- end -}}