{{- if .Values.dbpMoodle.restore.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: moodle-restore-script
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
data:
  restore-script: |-
{{- tpl ( .Files.Get "scripts/moodleRestoreScript.sh" ) . | nindent 4 -}}
{{- end }}