{{- if .Values.dbpMoodle.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: moodle-backup-script
  namespace: {{ .Release.Namespace }}
data:
  backup-script: |-
{{ tpl ( .Files.Get "scripts/backup.sh" ) . | indent 4 }}
{{- end }}