apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ include "moodlecronjob.job_name" . }}
  namespace: {{ .Release.Namespace }}
data:
  cronjob-script: |-
{{ tpl ( .Files.Get "scripts/moodleCronjobScript.sh" ) . | nindent 4 }}