{{- if .Values.dbpMoodle.update_migration.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-update-helper-job-script
  namespace: {{ .Release.Namespace }}
data:
  {{ .Release.Name }}-update-helper-job-script: |-
{{ tpl ( .Files.Get "scripts/moodleUpdateHelperJobScript.sh" ) . | indent 4 }}
{{- end }}