apiVersion: v2
appVersion: release-0102
dependencies:
- condition: phpldapadmin.enabled
  name: phpldapadmin
  repository: ""
  version: 0.1.x
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: ~2
description: Helm Chart for using community developed OpenLDAP software
home: https://www.openldap.org
keywords:
- ldap
- openldap
name: dbildungs-iam-ldap
version: 0.0.0-release-0102-20250116-1308
