{{- if .Values.dbpMoodle.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: moodle-autoscaler
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dbpMoodle.hpa.deployment_name_ref" . }}
  minReplicas: {{ .Values.dbpMoodle.hpa.min_replicas }}
  maxReplicas: {{ .Values.dbpMoodle.hpa.max_replicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.dbpMoodle.hpa.target_average_cpu_utilization }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.dbpMoodle.hpa.scale_up_stabilization_window_seconds }}
      selectPolicy: Max
      policies:
        - type: Percent
          value: {{ .Values.dbpMoodle.hpa.scaleup_value }}
          periodSeconds: {{ .Values.dbpMoodle.hpa.scaleup_cooldown }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.dbpMoodle.hpa.scale_down_stabilization_window_seconds }}
      selectPolicy: Max
      policies:
        - type: Percent
          value: {{ .Values.dbpMoodle.hpa.scaledown_value }}
          periodSeconds: {{ .Values.dbpMoodle.hpa.scaledown_cooldown }}
{{- end }}
