keycloakHostname: "keycloak.dev.spsh.dbildungsplattform.de"
keycloakPublic: false
# rootUrl is optional, if defined it will be set as rootUrl of client 'spsh'
rootUrl: "https://helm.dev.spsh.dbildungsplattform.de"
