{{- if .Values.dbpMoodle.backup.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "moodle-backup-job"
rules: {{- toYaml .Values.dbpMoodle.backup.rules | nindent 2 }}
{{- end -}}