{{ if not .Values.dbpMoodle.restore.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "moodle-update-preparation-hook-role"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules: {{- toYaml .Values.dbpMoodle.moodleUpdatePreparationHook.rules | nindent 2 }}
{{ end }}
