{{- if .Values.dbpMoodle.restore.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "moodle-restore-job"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules:
  {{- toYaml .Values.dbpMoodle.restore.rules | nindent 2 }}
{{- end }}
