apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openldap.fullname" $ }}-extraldif
  labels:
    app: {{ template "openldap.name" $ }}
    chart: {{ template "openldap.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
{{- if $.Values.extraLabels }}
{{ toYaml $.Values.extraLabels | indent 4 }}
{{- end }}
data:
  apply.ldif: |-
    dn: cn=lehrer,dc=schule-sh,dc=de
    cn: lehrer
    objectclass: groupOfUniqueNames
    objectclass: top

    dn: cn=schueler,dc=schule-sh,dc=de
    cn: schueler
    objectclass: groupOfUniqueNames
    objectclass: top

    dn: ou=oeffentlicheSchulen,dc=schule-sh,dc=de
    objectclass: organizationalUnit
    objectclass: top
    ou: oeffentlicheSchulen

    dn: cn=mmusterschueler,ou=oeffentlicheSchulen,dc=schule-sh,dc=de
    uid: mmusterschueler
    cn: mmusterschueler
    givenname: Moritz
    objectclass: inetOrgPerson
    objectclass: univentionMail
    mailPrimaryAddress: moritz.muster-schueler@schule-sh.de
    mailAlternativeAddress: moritz.muster-schueler@schule-sh.de
    objectclass: top
    sn: Muster-Schueler

    dn: cn=ssuperadmin,ou=oeffentlicheSchulen,dc=schule-sh,dc=de
    uid: ssuperadmin
    cn: ssuperadmin
    givenname: Susi
    objectclass: inetOrgPerson
    objectclass: univentionMail
    mailPrimaryAddress: susi.superadmin@schule-sh.de
    mailAlternativeAddress: susi.superadmin@schule-sh.de
    objectclass: top
    sn: Superadmin

  modify.ldif: |-
    # Group members
    dn: cn=lehrer,dc=schule-sh,dc=de
    cn: lehrer
    objectclass: groupOfUniqueNames
    objectclass: top
    dn: cn=lehrer,dc=schule-sh,dc=de
    uniquemember: cn=ssuperadmin,ou=oeffentlicheSchulen,dc=schule-sh,dc=de

    dn: cn=schueler,dc=schule-sh,dc=de
    cn: schueler
    objectclass: groupOfUniqueNames
    objectclass: top
    uniquemember: cn=mmusterschueler,ou=oeffentlicheSchulen,dc=schule-sh,dc=de