{{- if .Values.dbpMoodle.restore.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-restore-job"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: {{ .Values.dbpMoodle.restore.backoffLimit | default "4" }}
  template:
    spec:
      volumes:
      - name: moodle-data
        persistentVolumeClaim:
          claimName: {{ include "dbpMoodle.moodlePvc.name" . }}
      - name: moodle-restore-script
        configMap:
          name: "{{ .Release.Name }}-restore-script"
          defaultMode: 0711
      - name: duply
        projected:
          sources:
            - configMap:
                name: "{{ .Release.Name }}-duply"
                items:
                  - key: conf
                    path: conf
                  - key: exclude
                    path: exclude
            - secret:
                name: {{ .Values.dbpMoodle.restore.existingSecretGPG }}
          defaultMode: 0644
      serviceAccountName: "{{ .Release.Name }}-restore-job"
      serviceAccount: "{{ .Release.Name }}-restore-job"
      containers:
      - name:  moodle-restore-job
        image: {{ .Values.dbpMoodle.restore.image }}
        command:
          - /bin/sh
          - -c
        args:
          - /scripts/restore-script
        securityContext:
          privileged: false
        resources: 
          {{- .Values.dbpMoodle.restore.resources | toYaml | nindent 10 }}
        volumeMounts:
        - name: moodle-data
          mountPath: /bitnami/moodle
          subPath: moodle
        - name: moodle-data
          mountPath: /bitnami/moodledata
          subPath: moodledata
        - name: moodle-restore-script
          mountPath: /scripts/
        - name: duply
          mountPath: /etc/duply/default/
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbpMoodle.restore.existingSecretDatabase }}
              key: {{ .Values.dbpMoodle.restore.existingSecretKeyDatabase }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbpMoodle.restore.existingSecretS3 }}
              key: {{ .Values.dbpMoodle.restore.existingSecretKeyS3Access }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.dbpMoodle.restore.existingSecretS3 }}
              key: {{ .Values.dbpMoodle.restore.existingSecretKeyS3Secret }}
      affinity: {{ .Values.dbpMoodle.restore.affinity | toYaml }}
      tolerations: {{ .Values.dbpMoodle.restore.tolerations | toYaml }}
      restartPolicy: Never
{{- end }}
