global:
  kubectl_version: "1.28.7"
  storageClass: "nfs-client"
  moodlePlugins:
    kaltura:
      enabled: false
    etherpadlite:
      enabled: false
    hvp:
      enabled: false
    groupselect:
      enabled: false
    jitsi:
      enabled: false
    pdfannotator:
      enabled: false
    tiles:
      enabled: false
    skype:
      enabled: false
    zoom:
      enabled: false
    booking:
      enabled: false
    reengagement:
      enabled: false
    unilabel:
      enabled: false
    geogebra:
      enabled: false
    choicegroup:
      enabled: false
    staticpage:
      enabled: false
    heartbeat:
      enabled: false
    remuiformat:
      enabled: false
    topcoll:
      enabled: false
    oidc:
      enabled: false
    saml2:
      enabled: false
    dash:
      enabled: false
    sharing_cart:
      enabled: false
    xp:
      enabled: false
    certificate:
      enabled: false
    coursecertificate:
      enabled: false
    adaptable:
      enabled: false
    boost_union:
      enabled: false
    boost_magnific:
      enabled: false
    snap:
      enabled: false
dbpMoodle:
  name: infra
  stage: infra
  logging: false
  debug: false # Moodle debugging is not safe for production

  # The dbp update process to migrate moodle data when moodle versions are increased
  update_migration:
    enabled: false

  redis:
    host: "moodle-redis-master"
    port: 6379
    password: ""

  external_pvc:
    enabled: true
    name: "moodle-data"
    size: "8Gi"
    storage_class: "nfs-client"
    accessModes: ["ReadWriteOnce"]
    annotations:
      "helm.sh/resource-policy": "keep"

  secrets:
    useChartSecret: false
    moodle_password: ""
    pgsql_admin_password: ""
    mariadb_password: ""
    mariadb_root_password: ""
    etherpad_postgresql_password: ""
    etherpad_api_key: ""

  moodleUpdatePreparationJob:
    affinity: {}
    tolerations: []
    resources: {}
    kubectlImage: bitnami/kubectl:1.30.4-debian-12-r3

  moodleUpdatePreparationHook:
    rules:
      - apiGroups: ["apps"]
        resources: ["deployments"]
        verbs: ["get", "patch"]
      - apiGroups: ["batch"]
        resources: ["cronjobs", "jobs"]
        verbs: ["get", "list", "create", "patch", "watch"]

  backup:
    enabled: false
    gpg_key_names: ""
    gpgkeys:
      gpgkey.dbpinfra.pub.asc: ""
      gpgkey.dbpinfra.sec.asc: ""
      existingSecret: "" # existing secret for gpg keys
    s3_bucket_name: ""
    cluster_name: ""
    endpoint: ""
    secrets:
      s3_access_key: ""
      s3_access_secret: ""
      s3_endpoint_url: ""
      existingSecret: "" # existing secret for s3 secrets

    rules:
      - apiGroups: ["apps"]
        resources: ["deployments"]
        verbs: ["get", "patch", "list", watch]
      - apiGroups: ["batch"]
        resources: ["cronjobs", "jobs"]
        verbs: ["get", "patch"]

  restore:
    enabled: false # Only to be used to restore a snapshot with the dbp-restore script
    image: ghcr.io/dbildungsplattform/moodle-tools:1.0.7
    resources:
      limits:
        cpu: 2000m
        memory: 16Gi
      requests:
        cpu: 1000m
        memory: 8Gi
    existingSecretGPG: ""
    existingSecretDatabase: "moodle"
    existingSecretKeyDatabase: ""
    existingSecretS3: ""
    existingSecretKeyS3Access: ""
    existingSecretKeyS3Secret: ""
    affinity: {}
    tolerations: []

    rules:
      - apiGroups: ["apps"]
        resources: ["deployments/scale", "deployments"]
        verbs: ["get", "list", "scale", "patch"]

  moodlecronjob:
    wait_timeout: "15m"
    rules:
      - apiGroups: [""]
        resources: ["pods", "pods/exec"]
        verbs: ["get", "list", "create", "watch"]

  # Horizontal Pod Autoscaling Values
  hpa:
    enabled: false
    deployment_name_ref: "moodle"
    # Moodle Autoscaling Values
    min_replicas: 1
    max_replicas: 4
    average_cpu_utilization: 50
    # The up and downscaling values to have more control over the speed moodle will be scaled
    scaledown_value: 25 # The max amount in percent to scale in one step per cooldown period
    scaledown_cooldown: 60
    scaleup_value: 50
    scaleup_cooldown: 15

moodle:
  updateStrategy:
    type: RollingUpdate
  image:
    registry: ghcr.io
    repository: dbildungsplattform/moodle
    tag: "4.1.12-debian-12-r1-chart-main"
    pullPolicy: Always
    debug: false
  moodleSkipInstall: false
  moodleSiteName: "Moodle"
  moodleLang: "de"
  moodleUsername: admin
  moodleEmail: ""
  allowEmptyPassword: false
  extraEnvVars:
    - name: PHP_POST_MAX_SIZE
      value: "200M"
    - name: PHP_UPLOAD_MAX_FILESIZE
      value: "200M"
    - name: PHP_MAX_INPUT_VARS
      value: "5000"
    - name: MOODLE_PLUGINS
      valueFrom:
        configMapKeyRef:
          name: moodle-plugins
          key: moodle-plugin-list
  extraEnvVarsSecret: ""
  existingSecret: "moodle"
  persistence:
    existingClaim: "moodle-data"
  affinity: {}
  tolerations: []
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 6
      memory: 3Gi
  mariadb:
    enabled: false
  externalDatabase:
    type: "mariadb"
    host: "moodle-mariadb"
    port: 3306
    user: "moodle"
    database: "moodle"
    existingSecret: "moodle"
    password: ""
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostname: "example.de"
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: sc-cert-manager-clusterissuer-letsencrypt
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30s"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "20s"
      nginx.ingress.kubernetes.io/proxy-body-size: "200M"
  metrics:
    enabled: true
    service:
      type: ClusterIP
    resources: # We need those resources so the Horizontal Pod Autoscaler for moodle can read the moodle cpu consumption correctly
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 200m
        memory: 256Mi
  extraVolumeMounts:
    - name: moodle-config
      readOnly: true
      mountPath: /moodleconfig
  extraVolumes:
    - name: moodle-config
      secret:
        secretName: moodle-config
        items:
          - key: config.php
            path: config.php
          - key: php.ini
            path: php.ini
        defaultMode: 0644
  podAnnotations:
    moodle/image: '{{- .Values.image.repository -}}:{{- .Values.image.tag -}}'
    moodleplugins/checksum: '{{- include "dbpMoodle.pluginConfigMap.content" . | sha256sum -}}'
  containerSecurityContext:
    enabled: true
    runAsGroup: 1001
    runAsNonRoot: true
    privileged: false
  podSecurityContext:
    enabled: true
  containerPorts:
    http: 8080
    https: 8443
  networkPolicy:
    enabled: false

mariadb:
  enabled: true
  global:
    storageClass: "nfs-client"
  image:
    tag: "11.3.2-debian-12-r5"
  auth:
    username: "moodle"
    database: "moodle"
    existingSecret: "moodle"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  primary:
    containerSecurityContext:
      privileged: false
    affinity: {}
    tolerations: []
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 9
        memory: 3Gi

postgresql:
  enabled: false
  image:
    tag: "14.8.0-debian-11-r0"
  auth:
    username: "moodle"
    database: "moodle"
    existingSecret: "moodle"
    secretKeys:
      adminPasswordKey: "pgsql-admin-password"
      userPasswordKey: "mariadb-password" # moodle expects its db password key to be mariadb-password
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  primary:
    extendedConfiguration: |
      max_connections = 800
    containerSecurityContext:
      privileged: false
    affinity: {}
    tolerations: []
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: 9
        memory: "3Gi"

# redis helm chart values
redis:
  enabled: true
  architecture: "standalone"
  auth:
    enabled: true
    existingSecret: "moodle"
    existingSecretPasswordKey: "redis-password"
    usePasswordFileFromSecret: true
  master:
    affinity: {}
    tolerations: []
    resources: {}

etherpadlite:
  enabled: false
  image:
    repository: "ghcr.io/dbildungsplattform/etherpad"
    tag: "1.8.18.0"
  env:
    - name: DB_TYPE
      value: "postgres"
    - name: DB_HOST
      value: "moodle-etherpad-postgresql"
    - name: DB_PORT
      value: "5432"
    - name: DB_NAME
      value: "etherpad"
    - name: DB_USER
      value: "etherpad"
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: "moodle"
          key: "etherpad-postgresql-password"
    - name: REQUIRE_SESSION
      value: "true"
  volumes:
    - name: "api-key"
      secret:
        secretName: "moodle"
        items:
          - key: "etherpad-api-key"
            path: "APIKEY.txt"
  volumeMounts:
    - name: "api-key"
      mountPath: "/opt/etherpad-lite/APIKEY.txt"
      subPath: "APIKEY.txt"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "sc-cert-manager-clusterissuer-letsencrypt"
    hosts:
      - host: "etherpad.example.de"
        paths:
          - path: "/"
            pathType: "Prefix"
    tls:
      - secretName: "etherpad.example.de-tls"
        hosts:
          - "etherpad.example.de"
  securityContext:
    privileged: false
  affinity: {}
  tolerations: []
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"

etherpad-postgresql:
  auth:
    enablePostgresUser: false
    username: etherpad
    database: "etherpad"
    existingSecret: "moodle"
    secretKeys:
      userPasswordKey: "etherpad-postgresql-password"
  persistence:
    existingClaim: "moodle-etherpad-postgresql"
  primary:
    containerSecurityContext:
      privileged: false
    affinity: {}
    tolerations: []
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

moodlecronjob:
  image:
    repository: "ghcr.io/dbildungsplattform/moodle-tools"
    tag: "1.0.7"
  clusterRole:
    create: false
  serviceAccount:
    name: "moodle-moodle-cronjob"
    create: false
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsGroup: 1001
    capabilities:
      drop:
        - ALL
  affinity: {}
  tolerations: []
  resources: {}
  jobs:
    - name: php-script
      schedule: "* * * * *"
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: 1
      successfulJobsHistoryLimit: 1
      backoffLimit: 1
      restartPolicy: Never
      command:
        - /bin/bash
        - -c
      args:
        - /scripts/cronjob-script
      extraVolumeMounts:
        - name: moodle-php-script
          mountPath: /scripts/
      extraVolumes:
        - name: moodle-php-script
          configMap:
            name: moodle-php-script
            defaultMode: 0711

backup-cronjob:
  image:
    repository: "ghcr.io/dbildungsplattform/moodle-tools"
    tag: "1.0.7"
  clusterRole:
    create: false
  serviceAccount:
    name: "moodle-backup-job"
    create: false
  env:
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: moodle
          key: mariadb-password
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: moodle-backup-s3
          key: s3_access_key
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: moodle-backup-s3
          key: s3_access_secret
    - name: S3_BACKUP_REGION_URL
      valueFrom:
        secretKeyRef:
          name: moodle-backup-s3
          key: s3_endpoint_url
  extraVolumeMounts:
    - name: moodle-backup-script
      mountPath: /scripts/
    - name: moodle-pvc-data
      mountPath: /mountData
    - name: duply
      mountPath: /etc/duply/default/
  extraVolumes:
    - name: moodle-pvc-data
      persistentVolumeClaim:
        claimName: "moodle-data"
    - name: moodle-backup-script
      configMap:
        name: moodle-backup-script
        defaultMode: 0711
    - name: duply
      projected:
        sources:
          - configMap:
              name: moodle-duply
              items:
                - key: conf
                  path: conf
                - key: exclude
                  path: exclude
          - secret:
              name: moodle-backup-gpg-keys
        defaultMode: 0644
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsGroup: 1001
    capabilities:
      drop:
        - ALL
  affinity: {}
  tolerations: []
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
  jobs:
    - name: backup
      schedule: "0 3 * * *"
      failedJobsHistoryLimit: 1
      successfulJobsHistoryLimit: 1
      command:
        - /bin/sh
        - -c
      args:
        - /scripts/backup-script

sql-exporter:
  enabled: false
  image:
    pullPolicy: "IfNotPresent"
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
  affinity: {}
  tolerations: []
  resources: {}
  extraVolumes:
    - name: moodle-collector-config
      volume:
        configMap:
          name: moodle-sql-exporter-configmap
          items:
            - key: moodle-collector-config
              path: sql_exporter_moodle.yaml
      mount:
        readOnly: true
        mountPath: /etc/sql_exporter/collectors/
  config:
    collector_files: ["collectors/sql_exporter_moodle.yaml"]
    target:
      data_source_name: ""
      collectors: [sql_exporter_moodle]