name: Release Charts
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - OPS-6833-Dependencies_not_possible_in_helm-chart-releaser

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  #v4.1.1
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      # - name: Install yq
      #   run: sudo apt-get install -y yq

      - name: Extract and add dependencies
        run: |
          # Extract dependencies, filter for unique and starting with https
          repos=$(yq eval '.dependencies[].repository' automation/dbp-moodle/Chart.yaml | \
                  sort | \
                  uniq | \
                  grep '^https')

          # Loop through repositories and add them
          for repo in $repos; do
              echo "Adding repo \"$(basename "$repo")\" with source \"$repo\""
              helm repo add "$(basename "$repo")" "$repo" || echo "Failed to add \"$repo\""
          done

      # - name: Add Helm dependencies
      #   run: |
      #     helm repo add bitnami https://charts.bitnami.com/bitnami
      #     helm repo add sql_exporter https://burningalchemist.github.io/sql_exporter/

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584   #v1.6.0
      #   with:
      #     charts_dir: automation
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # - uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
      #   if: failure()
      #   with:
      #     type: ${{ job.status }} 
      #     job_name: 'Helmchart Release Status: '
      #     url: ${{ secrets.RC_WEBHOOK }}
      #     channel: '#dbp-dev-monitoring'
      #     username: Helmchart Failure Notificator
        
      
