name: Release Charts
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - DBP-679-create-release-gha

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  #v4.1.1
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584   #v1.6.0
        with:
          charts_dir: automation
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"


